apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: suyashgaikwad/mern-suyashcafe:1.1-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb+srv://suyashus:KSmn1Ww4JyTOrTSA@cluster0.e2i8x.mongodb.net/menu?retryWrites=true&w=majority&appName=Cluster0" # Use your actual remote MongoDB URL
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001  # <-- Exposes backend externally on port 30001
  type: NodePort  # <-- Change this line from ClusterIP to NodePort

