apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: suyashgaikwad/mern-suyashcafe:1.1-frontend  # <-- Make sure this is correct
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        env:
        - name: VITE_BACKEND_URL
          value: "http://backend-service:3000"  # <-- Update to use the new backend URL

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5173
  type: LoadBalancer  # Exposes frontend publicly

